baseurl = ""
title = ""
theme = "hugo-shows"
languageCode = "en-us"
paginate = 5

[menu]
  # Shown in the side menu.
  [[menu.main]]
    name = "shows"
    weight = 0
    url = "/shows"
  [[menu.main]]
    name = "about"
    weight = 1
    url = "/about"

# Enable analytics by entering your Google Analytics tracking ID
googleAnalytics = "UA-123456789-0"

[params]
  Keywords = ""
  Description = ""

  Avater = ""
  SelfIntro = ""
  Email = ""

  #GithubID = "Your Github ID"
  TwitterID = ""
  FacebookID = ""
  #YouTubeID = ""
  #GoogleplusID = "Your Googleplus ID"


  [params.social]
        #github      = "albush"
        facebook        = ""
        facebook_admin  = ""  # This needs to be a page admin to get domain insights
        twitter     = ""
        twitter_domain  = "" # This domain shows in twitter cards as "View on `twitter_domain`"
        #googleplus      = ""
        instagram       = ""
        # youtube     = ""
        [params.authors]
        [params.authors.xxx]
        name          = ""
        thumbnail     = ""
        images        = [
                        "",
                      ]
        bio           = ""
        email         = ""
